[package]
name = "epbdrs"
version = "0.1.0"
authors = ["Rafael Villar Burke <pachi@ietcc.csic.es>"]

[dependencies]
failure = "*"
lazy_static = "*"
maplit = "*"
num= "*"
strum = "*"
strum_macros = "*"

[dev-dependencies]
pretty_assertions = "*"

#[profile.release]
#debug = true
#opt-level = "z"
#lto = true