[package]
name = "cteepbd"
version = "0.9.3"
authors = ["Rafael Villar Burke <pachi@ietcc.csic.es>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
exitcode = "1.1.2"
failure = "0.1.2"
itertools = "0.7.8"
num= "0.2.0"
serde = "1.0.72"
serde_json = "1.0.26"
serde_derive = "1.0.72"
strum = "0.10.0"
strum_macros = "0.10.0"

[dev-dependencies]
pretty_assertions = "0.5.1"
assert_cli = "0.6.3"

#[profile.release]
#debug = true
#opt-level = "z"
#lto = true
