[package]
name = "epbdrs"
version = "0.9.1"
authors = ["Rafael Villar Burke <pachi@ietcc.csic.es>"]

[dependencies]
clap = "*"
exitcode = "*"
failure = "*"
itertools = "*"
num= "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
strum = "*"
strum_macros = "*"

[dev-dependencies]
pretty_assertions = "*"
assert_cli = "*"

#[profile.release]
#debug = true
#opt-level = "z"
#lto = true
