[package]
name = "epbdrs"
version = "0.1.0"
authors = ["Rafael Villar Burke <pachi@ietcc.csic.es>"]

[dependencies]
failure = "*"
lazy_static = "*"
maplit = "*"
strum = "0.9.0"
strum_macros = "0.9.0"

[dev-dependencies]
pretty_assertions = "*"